name: Sequential Jobs

on:
    push:
        branches: [ master ]

    workflow_dispatch:

jobs:
    myJob:
        name: ${{matrix.config.gameid}}
        runs-on: ubuntu-latest

        strategy:
            max-parallel: 1
            matrix:
                config:
                    - { gameid: 'CK3', steam_appid: '1158310', steam_itemid: '2217534250', dirname: 'more-cultural-names' }
                    - { gameid: 'CK3AE', steam_appid: '1158310', steam_itemid: '2830250537', dirname: 'ae-more-cultural-names' }
                    - { gameid: 'CK3CMH', steam_appid: '1158310', steam_itemid: '2813306520', dirname: 'cmh-more-cultural-names' }
                    - { gameid: 'CK3IBL', steam_appid: '1158310', steam_itemid: '2490281800', dirname: 'ibl-more-cultural-names' }

        steps:
            - name: Prepare
              run: |
                echo "GameId: ${{matrix.config.gameid}}, SteamAppId: ${{matrix.config.steam_appid}}, SteamItemId: ${{matrix.config.steam_itemid}}, DirName: ${{matrix.config.dirname}}"

            - name: Wait
              run: |
                WAIT_SEC=10
                echo "Waiting ${WAIT_SEC} seconds..."
                sleep ${WAIT_SEC}
