name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release (CK3)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Prepare assets
      run: |
        mkdir "CK3"
        wget "https://github.com/hmlendea/more-cultural-names/releases/download/v22.344.0/mcn_CK3_22.344.0.zip" -O "CK3.zip"
        unzip "CK3.zip" -d "CK3/"

    - name: Install dependencies
      run: apt install libicu

    - name: Crusader Kings 3
      uses: hmlendea/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2462509364
        path: "CK3/more-cultural-names/"
        changenote: "[url=https://steamcommunity.com/linkfilter/?url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_TFASEED}}
