name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release (CK3)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Prepare assets
      run: |
        for GAME_ID in "CK2" "CK3"; do
          mkdir "${GAME_ID}"
          wget "https://github.com/hmlendea/testRepo/releases/download/${{github.ref_name}}/mcn_${GAME_ID}_${GITHUB_REF:11}.zip" -O "${GAME_ID}.zip"
          unzip "${GAME_ID}.zip" -d "${GAME_ID}/"
        done 
        sed -i 's/^path\s*=.*/archive=\"more-cultural-names.zip\"/g' CK2/more-cultural-names.mod
        cp CK2/more-cultural-names.mod CK2/more-cultural-names/descriptor.mod
        cd CK2/more-cultural-names && zip -r more-cultural-names.zip . && cd -
        mv CK2/more-cultural-names/more-cultural-names.zip CK2/
        rm -rf CK2/more-cultural-names/
        ls CK2/
        du -sh CK2/*

    - name: Crusader Kings 2
      uses: hmlendea/steam-workshop-upload@v1
      with:
        appid: 203770
        itemid: 2687533945
        path: "CK2/more-cultural-names.zip"
        changenote: "[url=https://steamcommunity.com/linkfilter/?url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_TFASEED}}

    - name: Crusader Kings 3
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2462509364
        path: "CK3/more-cultural-names/"
        changenote: "[url=https://steamcommunity.com/linkfilter/?url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_TFASEED}}
