name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Steam Workshop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download release assets
      run: |
        CURRENT_VERSION=${GITHUB_REF:11}
        echo VERSION=${CURRENT_VERSION} >> $GITHUB_ENV
        wget "https://github.com/hmlendea/testRepo/releases/download/v${CURRENT_VERSION}/mcn_CK3_${CURRENT_VERSION}.zip"

    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1

    - name: Generate auth code
      id: generate
      uses: CyberAndrii/steam-totp@v1
      with:
        shared_secret: ${{ secrets.STEAM_2FA_SEED }}

    - uses: hmlendea/workshop-upload@v2
      with:
        appId: '1158310'
        itemId: '2462509364'
        contentPath: './mcn_CK3_${{ env.VERSION }}.zip'
        changelog: '${{ env.VERSION }}'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        STEAM_2FA_CODE: ${{ steps.generate.outputs.code }}
