name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Steam Workshop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
    - uses: arma-actions/workshop-upload@v1
      with:
        appId: '1158310'
        itemId: '2462509364'
        contentPath: 'releases/mcn_CK3_${{ env.VERSION }}.zip'
        changelog: '${{ env.VERSION }}'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
