name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download release assets
      run: |
        CURRENT_VERSION=${GITHUB_REF:11}
        echo VERSION=${CURRENT_VERSION} >> $GITHUB_ENV
        wget "https://github.com/hmlendea/testRepo/releases/download/v${CURRENT_VERSION}/mcn_CK3_${CURRENT_VERSION}.zip"
    - name: steam-workshop-upload
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2462509364
        path: "mcn_CK3_${{ env.VERSION }}.zip"
        changenote: "[url=https://steamcommunity.com/linkfilter/?url=https://github.com/hmlendea/more-cultural-names/releases/tag/v${{ env.VERSION}}]Version ${{ env.VERSION }}[/url]"
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }}
