name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release (CK3)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download release assets
      run: wget "https://github.com/hmlendea/testRepo/releases/download/${{github.ref_name}}/mcn_CK3_${GITHUB_REF:11}.zip" -O "mcn.zip"
    - name: steam-workshop-upload
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2462509364
        path: "mcn.zip"
        changenote: "[url=https://steamcommunity.com/linkfilter/?url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_TFASEED}}
